Create 7 Day Writing Challenge.md
AskDevs/Technical-Writing-Practice pull request #1
Opened 2023-02-14 16:02 UTC by codewithshubhi

2023-02-16 20:39 UTC, OkelloSam21 approved these changes

2023-02-17 21:57 UTC, codewithvoid requested changes

2023-02-17 21:57 UTC, codewithvoid commented on 7 Day Writing Challenge/Rules.md
> +# ✍️ 7 Day Writing Challenge
rename this to announcement.md

2023-02-17 21:57 UTC, codewithvoid commented on 7 Day Writing Challenge/Step_1.md
> +## 🔶 Step1.Topic/Idea
rename this file to day 1.md

2023-02-17 21:57 UTC, codewithvoid commented on 7 Day Writing Challenge/Step_1.md
> +You can brainstorm in a bunch of different ways, including as a group, but here's the approach to it that works best for me:
format this better.

2023-02-17 21:57 UTC, codewithvoid commented on 7 Day Writing Challenge/Step_2.md
> +Google as much as possible, get facts and figures from research journals, books or news, and gather as much information as you can about your topic. Then you can start making an outline.
- Shorten the steps
- Put it in a form of 1.2.3
- Give examples wherever necessary

2023-02-20 13:15 UTC, codewithvoid commented on 7 Day Writing Challenge/announcement.md
> +**🔶 Step7.Share**: Once you’ve actually published the post, you’re not done! If you want people to see what you’ve written and get value out of it, make sure to share it in the places where your audi
publish and share can be together

2023-02-20 13:25 UTC, codewithvoid commented on 7 Day Writing Challenge/Day_1.md
> +## 🔶 Day 1. Topic/Idea
rename folder name to 7_DAY_CHALLENGE

2023-02-20 13:25 UTC, codewithvoid commented on 7 Day Writing Challenge/announcement.md
> +Within a week, you undeniably learnt a thing or two, to add with that, you wrote an article, so congratulate yourself.
add new line here

2023-02-20 13:25 UTC, codewithvoid commented on 7 Day Writing Challenge/announcement.md
> +When you have a question, hit up the `#7day-writing-challenge` [channel](https://discord.com/channels/1073966100552896632/1073983804437450763) .
update channel name to writing-discuss

2023-02-20 13:25 UTC, codewithvoid commented on 7 Day Writing Challenge/announcement.md
> +Well, I guess the challenge has been explained enough. If you need more clarifications, kindly reach me on [twitter]() by using #Askdevs
`I guess the challenge has been explained enough.` remove this line

2023-02-20 13:25 UTC, codewithvoid commented on 7 Day Writing Challenge/announcement.md
> +Well, I guess the challenge has been explained enough. If you need more clarifications, kindly reach me on [twitter]() by using #Askdevs
add askdevs intent link

2023-02-20 13:25 UTC, codewithvoid commented on 7 Day Writing Challenge/announcement.md
> +Let's get you some open-source rep!!!
nit: Let's get your first blogpost published.

2023-02-20 13:25 UTC, codewithvoid commented on 7 Day Writing Challenge/announcement.md
> +At the very least, drop a ⭐ on the repo if you're feeling fancy!
Leave a star to support us 🙏

2023-02-20 13:25 UTC, codewithvoid commented on 7 Day Writing Challenge/announcement.md
> +Commit to the Challenge Now!!
Join the community and commit to the challenge now!

Add discord link.

2023-02-20 14:16 UTC, codewithshubhi commented
closing this.

2023-02-20 14:16 UTC, closed without merging